/**
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

// Byte per audio sample (32-bit float = 4 bytes).
const BYTES_PER_SAMPLE = Float32Array.BYTES_PER_ELEMENT;

// The max audio channel count on Chrome is 32.
const MAX_CHANNEL_COUNT = 32;

// WebAudio render quantum size.
const RENDER_QUANTUM_FRAMES = 128;

/**
 * A WASM HEAP wrapper for AudioBuffer class. This breaks down the AudioBuffer
 * into an Array of Float32Array views for convenient WASM heap operations.
 *
 * @class FreeQueue
 */
class FreeQueue {
  /**
   * @constructor
   * @param {object} wasmModule WASM module generated by Emscripten.
   * @param {number} length Buffer frame length.
   * @param {number} channelCount Number of channels.
   * @param {number} [maxChannelCount] Maximum number of channels.
   */
  constructor(wasmModule, length, channelCount, maxChannelCount) {
    this._isInitialized = false;
    this._module = wasmModule;
    this._length = length;
    this._maxChannelCount = maxChannelCount
      ? Math.min(maxChannelCount, MAX_CHANNEL_COUNT)
      : channelCount;
    this._channelCount = channelCount;
    this._allocateHeap();
    this._isInitialized = true;

    // RingBuffer state initialization
    this._readIndex = 0;
    this._writeIndex = 0;
    this._framesAvailable = 0;
    this._channelDataLocal = [];
    for (let i = 0; i < this._channelCount; ++i) {
      this._channelDataLocal[i] = new Float32Array(length);
    }
  }

  /**
   * Allocates memory in WASM heap and sets up Float32Array views.
   * @private
   */
  _allocateHeap() {
    const channelByteSize = this._length * BYTES_PER_SAMPLE;
    const dataByteSize = this._channelCount * channelByteSize;
    this._dataPtr = this._module._malloc(dataByteSize);
    this._channelData = [];
    for (let i = 0; i < this._channelCount; ++i) {
      const startByteOffset = this._dataPtr + i * channelByteSize;
      const endByteOffset = startByteOffset + channelByteSize;
      this._channelData[i] = this._module.HEAPF32.subarray(
        startByteOffset / BYTES_PER_SAMPLE,
        endByteOffset / BYTES_PER_SAMPLE
      );
    }
  }

  /**
   * Adapt current channel count to new input buffer.
   * @param {number} newChannelCount
   */
  adaptChannel(newChannelCount) {
    if (newChannelCount < this._maxChannelCount) {
      this._channelCount = newChannelCount;
    }
  }

  /**
   * Buffer length in frames.
   * @return {?number}
   */
  get length() {
    return this._isInitialized ? this._length : null;
  }

  /**
   * Number of channels.
   * @return {?number}
   */
  get numberOfChannels() {
    return this._isInitialized ? this._channelCount : null;
  }

  /**
   * Maximum channels allowed.
   * @return {?number}
   */
  get maxChannelCount() {
    return this._isInitialized ? this._maxChannelCount : null;
  }

  /**
   * Returns Float32Array for given channel index.
   * @param {number} [channelIndex]
   * @return {Float32Array|Float32Array[]}
   */
  getChannelData(channelIndex) {
    if (channelIndex >= this._channelCount) {
      return null;
    }
    return typeof channelIndex === 'undefined'
      ? this._channelData
      : this._channelData[channelIndex];
  }

  /**
   * Returns base address of allocated memory space in WASM heap.
   * @return {number}
   */
  getHeapAddress() {
    return this._dataPtr;
  }

  /**
   * Returns base address of allocated memory space in WASM heap.
   * @return {number}
   */
  getPointer() {
    return this._dataPtr;
  }

  /**
   * Frees allocated memory in WASM heap.
   */
  free() {
    this._isInitialized = false;
    this._module._free(this._dataPtr);
    this._channelData = null;
  }

  /**
   * Available frames in buffer.
   * @return {number}
   */
  get framesAvailable() {
    return this._framesAvailable;
  }

  /**
   * Push a sequence of Float32Arrays to buffer.
   * @param {Float32Array[]} arraySequence
   */
  push(arraySequence) {
    if (arraySequence.length !== this._channelCount) {
      throw new Error(
        `Channel count mismatch: expected ${this._channelCount}, ` +
          `got ${arraySequence.length}.`
      );
    }

    const sourceLength = arraySequence[0].length;
    for (let i = 0; i < sourceLength; ++i) {
      for (let channel = 0; channel < this._channelCount; ++channel) {
        this._channelDataLocal[channel][this._writeIndex] =
          arraySequence[channel][i];
      }
      this._writeIndex = (this._writeIndex + 1) % this._length;
    }

    this._framesAvailable += sourceLength;
    if (this._framesAvailable > this._length) {
      this._framesAvailable = this._length;
    }
  }

  /**
   * Pull data out of buffer and fill arraySequence.
   * @param {Float32Array[]} arraySequence
   */
  pull(arraySequence) {
    if (arraySequence.length !== this._channelCount) {
      throw new Error(
        `Channel count mismatch: expected ${this._channelCount}, ` +
          `got ${arraySequence.length}.`
      );
    }

    if (this._framesAvailable === 0) {
      return;
    }

    const destinationLength = arraySequence[0].length;
    for (let i = 0; i < destinationLength; ++i) {
      for (let channel = 0; channel < this._channelCount; ++channel) {
        arraySequence[channel][i] =
          this._channelDataLocal[channel][this._readIndex];
      }
      this._readIndex = (this._readIndex + 1) % this._length;
    }

    this._framesAvailable -= destinationLength;
    if (this._framesAvailable < 0) {
      this._framesAvailable = 0;
    }
  }
}

export { MAX_CHANNEL_COUNT, RENDER_QUANTUM_FRAMES, FreeQueue };
